### ISSUE TITLE
ImportError: libcudart.so.9.0:

### ISSUE THREAD

**Issue by gaoyh18** [microsoft/human-pose-estimation.pytorch#129]
I meet the same question postde in #44 but little different.
> Traceback (most recent call last):
  File "pose_estimation/train.py", line 37, in <module>
    import dataset
  File "/home/gyh/human-pose-estimaion/pose_estimation/../lib/dataset/__init__.py", line 12, in <module>
    from .coco import COCODataset as coco
  File "/home/gyh/human-pose-estimaion/pose_estimation/../lib/dataset/coco.py", line 23, in <module>
    from nms.nms import oks_nms
  File "/home/gyh/human-pose-estimaion/pose_estimation/../lib/nms/nms.py", line 14, in <module>
    from .gpu_nms import gpu_nms
ImportError: libcudart.so.9.0: cannot open shared object file: No such file or directory

When I follow the step 5, the output is 
> cd nms; python setup.py build_ext --inplace; rm -rf build; cd ../../
running build_ext
skipping 'cpu_nms.c' Cython extension (up-to-date)
skipping 'gpu_nms.cpp' Cython extension (up-to-date)

I'm not sure whether it's correct or not, or there are some problems with the vision of CUDA, which is 8.0.

**Comment by gaoyh18** [comment]
I check the '/usr/local/cuda/lib64' later, and there is 'libcudart.so.8.0' instead of 'libcudart.so.9.0' actually.
Then, what's the problem? 
> \>>> import torch
\>>> torch.version.cuda
'8.0.61'
\>>> torch.cuda.is_available()
True
\>>> torch.backends.cudnn.version()
7102

**Comment by gaoyh18** [comment]
> sudo su
cd user/local/cuda/lib64
ln -s libcudart.so.8.0 libcudart.so.9.0

The problem has been solved!
